version: '3'

# configuration file to use with https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion
# In order to run:
#  1. docker network create webproxy
#  2. Start the proxy
#  3. Configure DOMAIN_NAME and ADMIN_EMAIL in .env
#  4. docker-compose -f docker-compose.yml -f docker-compose.letsencrypt.yml up --build -d

services:
  gitexercises:
    networks: [proxy]
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    expose: [80]

networks:
  proxy:
    external:
      name: webproxy
